import { createFileRoute, Link } from "@tanstack/react-router";
import { Mail, FileText, ListChecks, Search, MessageSquare, ArrowRight, Sparkles } from "lucide-react";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Dashboard — Workplace AI" },
      { name: "description", content: "Your AI-powered workplace productivity dashboard." },
    ],
  }),
  component: Dashboard,
});

const tools = [
  { url: "/email", title: "Smart Email Generator", desc: "Draft professional emails in seconds.", icon: Mail },
  { url: "/meetings", title: "Meeting Notes Summarizer", desc: "Turn raw notes into clear summaries & actions.", icon: FileText },
  { url: "/tasks", title: "AI Task Planner", desc: "Break goals into prioritized, scheduled tasks.", icon: ListChecks },
  { url: "/research", title: "AI Research Assistant", desc: "Quick briefings on any topic.", icon: Search },
  { url: "/chat", title: "AI Chatbot", desc: "Ask anything, brainstorm, iterate.", icon: MessageSquare },
];

function Dashboard() {
  return (
    <div className="mx-auto w-full max-w-6xl px-4 py-10 md:px-8">
      <div className="mb-10 overflow-hidden rounded-2xl border bg-gradient-to-br from-primary/10 via-background to-accent/30 p-8 md:p-10">
        <div className="flex items-center gap-2 text-xs font-medium text-primary">
          <Sparkles className="h-3.5 w-3.5" /> AI productivity suite
        </div>
        <h1 className="mt-3 text-3xl font-semibold tracking-tight md:text-4xl">
          Automate the busywork. Focus on what matters.
        </h1>
        <p className="mt-3 max-w-2xl text-muted-foreground">
          Workplace AI brings together email drafting, meeting summaries, task planning,
          research and chat into one clean, professional workspace.
        </p>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {tools.map((t) => (
          <Link
            key={t.url}
            to={t.url}
            className="group rounded-xl border bg-card p-5 transition-all hover:-translate-y-0.5 hover:border-primary/40 hover:shadow-md"
          >
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent text-accent-foreground">
              <t.icon className="h-5 w-5" />
            </div>
            <h3 className="mt-4 font-semibold">{t.title}</h3>
            <p className="mt-1 text-sm text-muted-foreground">{t.desc}</p>
            <div className="mt-4 inline-flex items-center text-xs font-medium text-primary opacity-0 transition-opacity group-hover:opacity-100">
              Open <ArrowRight className="ml-1 h-3 w-3" />
            </div>
          </Link>
        ))}
      </div>

      <div className="mt-10 rounded-xl border bg-muted/30 p-5 text-sm text-muted-foreground">
        <p className="font-medium text-foreground">Responsible AI</p>
        <p className="mt-1">
          Outputs are generated by AI and may be inaccurate, incomplete, or biased.
          Always review and verify before sharing externally or making decisions based on them.
          Avoid entering confidential personal data.
        </p>
      </div>
    </div>
  );
}
